Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for dtheta0 in [1, 2, 3, 4, 5]:
    Z = np.array([[1, 1], 
                  [np.sqrt(g/L), -np.sqrt(g/L)]])
    x0 = np.array([-1.2, dtheta0])

    AB = np.linalg.solve(Z, x0)

    L = 0.8 #m
    g = 9.81 # m/s/s
    e = 2.71828
    t = np.linspace(0, 0.7) #4*np.pi) # 2 time periods of motion
    theta = AB[0]*np.exp(3.5*t) + AB[1]*np.exp(-3.5*t)
    dtheta = np.sqrt(g/L)*(AB[0]*np.exp(3.5*t) - AB[1]*np.exp(-3.5*t))
    ddtheta = g/L*(theta)

    plt.plot(t, theta*180/np.pi)
plt.title('angle in degrees')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 3[0m
[1;32m      1[0m [38;5;28;01mfor[39;00m dtheta0 [38;5;129;01min[39;00m [[38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m3[39m, [38;5;241m4[39m, [38;5;241m5[39m]:
[1;32m      2[0m     Z [38;5;241m=[39m np[38;5;241m.[39marray([[[38;5;241m1[39m, [38;5;241m1[39m], 
[0;32m----> 3[0m                   [np[38;5;241m.[39msqrt([43mg[49m[38;5;241m/[39mL), [38;5;241m-[39mnp[38;5;241m.[39msqrt(g[38;5;241m/[39mL)]])
[1;32m      4[0m     x0 [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m-[39m[38;5;241m1.2[39m, dtheta0])
[1;32m      6[0m     AB [38;5;241m=[39m np[38;5;241m.[39mlinalg[38;5;241m.[39msolve(Z, x0)

[0;31mNameError[0m: name 'g' is not defined

