Traceback (most recent call last):
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/ryan/.conda/envs/newwork/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from IPython.core.display import SVG
SVG(filename='../dyn-logo.svg')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m SVG
[0;32m----> 2[0m [43mSVG[49m[43m([49m[43mfilename[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m../dyn-logo.svg[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/.conda/envs/newwork/lib/python3.9/site-packages/IPython/core/display.py:327[0m, in [0;36mDisplayObject.__init__[0;34m(self, data, url, filename, metadata)[0m
[1;32m    324[0m [38;5;28;01melif[39;00m [38;5;28mself[39m[38;5;241m.[39mmetadata [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    325[0m     [38;5;28mself[39m[38;5;241m.[39mmetadata [38;5;241m=[39m {}
[0;32m--> 327[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mreload[49m[43m([49m[43m)[49m
[1;32m    328[0m [38;5;28mself[39m[38;5;241m.[39m_check_data()

File [0;32m~/.conda/envs/newwork/lib/python3.9/site-packages/IPython/core/display.py:353[0m, in [0;36mDisplayObject.reload[0;34m(self)[0m
[1;32m    351[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mfilename [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    352[0m     encoding [38;5;241m=[39m [38;5;28;01mNone[39;00m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_read_flags [38;5;28;01melse[39;00m [38;5;124m"[39m[38;5;124mutf-8[39m[38;5;124m"[39m
[0;32m--> 353[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfilename[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_read_flags[49m[43m,[49m[43m [49m[43mencoding[49m[38;5;241;43m=[39;49m[43mencoding[49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m    354[0m         [38;5;28mself[39m[38;5;241m.[39mdata [38;5;241m=[39m f[38;5;241m.[39mread()
[1;32m    355[0m [38;5;28;01melif[39;00m [38;5;28mself[39m[38;5;241m.[39murl [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    356[0m     [38;5;66;03m# Deferred import[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../dyn-logo.svg'
FileNotFoundError: [Errno 2] No such file or directory: '../dyn-logo.svg'

